title: Rickon Zhang
email: rickon.zhang@gmail.com
url: "https://rickonz.github.io" 
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to my blog!
show_excerpts: true # set to true to show excerpts on the homepage

markdown: kramdown
github: [metadata]

# Build settings
remote_theme: thelehhman/texture
theme: texture
plugins:
  - jekyll-feed
  
permalink: /posts/:title/
texture:
  title: Rickon Zhang
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showPicker: false
  analytics_id: ''
  showNav: true
  navigation: 
    - title: My Work
      url: "https://rickonz.github.io/my-work"
    - title: Resume
      url: "https://rickonz.github.io/resume"
    - title: About
      url "https://rickonz.github.io/about"

  social_links:
    github:  rickonz
    linkedIn: in/wenxuan-zhang
    instagram: xuanedx



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
