title: Rickon Zhang
email: rickon.zhang@gmail.com
url: "https://rickonz.github.io" 
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to my blog!
show_excerpts: true # set to true to show excerpts on the homepage

markdown: kramdown
mathjax: true
github: [metadata]

# Build settings
remote_theme: thelehhman/texture
plugins:
  - jekyll-feed
  

texture:
  title: Rickon Zhang
  tagline: 'Developer. Designer'
  date_format: "%b %-d, %Y"
  style: black
  showPicker: false
  analytics_id: '65691107'
  showNav: true
  navigation: 
    - title: Home
      url: "https://rickonz.github.io"
    - title: About
      url: "/about"
    - title: Resume
      url: "/resume"
  

  social_links:
    github:  rickonz
    linkedIn: in/wenxuan-zhang



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
